### ISSUE TITLE
能否仅限SUPERUSERS以及管理可操作（）

### ISSUE THREAD

**Issue by rainyorange** [MeetWq/nonebot-plugin-withdraw#5]
要不安个rt的开关也行（）

**Comment by MeetWq** [comment]
这个插件目的就是让群友自助撤回一些消息
管理员本来就能撤回成员消息，仅限管理员操作有什么意义呢？

**Comment by rainyorange** [comment]
（）忘记了管理也可以了，因为superusers不是管理的话不就（）
忽略了这个问题（）
