### ISSUE TITLE
建议加上权限

### ISSUE THREAD

**Issue by QwindF** [MeetWq/nonebot-plugin-withdraw#7]
```
from nonebot.permission import SUPERUSER
withdraw = on_command("withdraw", aliases={"撤回","recall"}, block=True, rule=smart_to_me,permission=SUPERUSER)
```

**Comment by MeetWq** [comment]
这个插件的目的就是让群友自助撤回一些不合适消息
加权限就没有意义了

**Comment by QwindF** [comment]
> 这个插件的目的就是让群友自助撤回一些不合适消息 加权限就没有意义了

哦抱歉，是我没明白这个插件的初衷了。
但是我建议你把这一特点加入README（我一直以为只有主人可以执行操作），由于我机器人在大部分群有管理员权限，导致了部分别有用心的人可以乱撤回消息。
或者单独写个管理人员名单，把这个撤回的权限给予在群众信任度高且活跃的人，以上是我的建议

**Comment by MeetWq** [comment]
我暂时不会加这些东西，
你可以考虑用 [插件管理器](https://github.com/nonepkg/nonebot-plugin-manager) 来实现

**Comment by QwindF** [comment]
好的，谢谢你的回答
